export const WELCOME_IMAGE = 'WELCOME_IMAGE'
export const LOADING_SPINNER = 'LOADING_SPINNER'
export const NOTIFICATION_FEED = 'NOTIFICATION_FEED'
export const NOTIFICATION_CARD = 'NOTIFICATION_CARD'
